name: Matrix Demo
on: push
jobs:
    build:
        # Using strategy like that, this job will run for
        # Node 18 on ubuntu-latest, Node 18 on windows-latest
        # Node 20 on ubuntu-latest, Node 18 on windows-latest
        # Node 22 on ubuntu-latest, Node 18 on windows-latest
        strategy:
            matrix:
                node-version: [18, 20, 22]
                operating-system: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build project
              run: npm run build